/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7_paulinaeuceda;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;

/**
 *
 * @author euced
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();

        dc_fecha.setDate(new Date());
        adminUsuario l = new adminUsuario("./Usuario.cbm");
        l.cargarArchivo();
        DefaultComboBoxModel modelo = new DefaultComboBoxModel(l.getlistaUsuarios().toArray());
        cb_artistas.setModel(modelo);

        adminBanda ban = new adminBanda("./Banda.cbm");
        ban.cargarArchivo();
        DefaultComboBoxModel modelo1 = new DefaultComboBoxModel(ban.getListaBandas().toArray());
        cb_sol.setModel(modelo1);

        adminSolista sol = new adminSolista("./Solista.cbm");
        sol.cargarArchivo();
        DefaultComboBoxModel modelo2 = new DefaultComboBoxModel(sol.getListaSolista().toArray());
        cb_ban.setModel(modelo2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_registrar = new javax.swing.JDialog();
        tf_username = new javax.swing.JTextField();
        tf_display = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pf_contrasena = new javax.swing.JPasswordField();
        jb_crear = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        pb_registro = new javax.swing.JProgressBar();
        jLabel7 = new javax.swing.JLabel();
        jd_admin = new javax.swing.JDialog();
        jButton4 = new javax.swing.JButton();
        elim = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jd_tablaAdmin = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jd_eliminar = new javax.swing.JDialog();
        jButton8 = new javax.swing.JButton();
        cb_artistas = new javax.swing.JComboBox<>();
        jd_elimSol = new javax.swing.JDialog();
        jButton9 = new javax.swing.JButton();
        cb_sol = new javax.swing.JComboBox<>();
        jd_elimBan = new javax.swing.JDialog();
        jButton10 = new javax.swing.JButton();
        cb_ban = new javax.swing.JComboBox<>();
        jd_artista = new javax.swing.JDialog();
        jButton7 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jd_evento = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tf_ciudad = new javax.swing.JTextField();
        jp_personas = new javax.swing.JSpinner();
        dc_fecha = new com.toedter.calendar.JDateChooser();
        tf_lugar = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        pb_evento = new javax.swing.JProgressBar();
        jLabel11 = new javax.swing.JLabel();
        jd_cancion = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_nomCan = new javax.swing.JTextField();
        jp_segundos = new javax.swing.JSpinner();
        jButton12 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jd_agregarC = new javax.swing.JDialog();
        cb_canciones = new javax.swing.JComboBox<>();
        jButton14 = new javax.swing.JButton();
        pb_cancion = new javax.swing.JProgressBar();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_userL = new javax.swing.JTextField();
        pf_contra = new javax.swing.JPasswordField();
        jb_login = new javax.swing.JButton();
        jb_ingresar = new javax.swing.JButton();
        lb_foto = new javax.swing.JLabel();

        jd_registrar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jd_registrar.getContentPane().add(tf_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 150, 30));
        jd_registrar.getContentPane().add(tf_display, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 150, 30));

        jLabel2.setText("Nombre");
        jd_registrar.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        jLabel3.setText("Contraseña");
        jd_registrar.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        jLabel4.setText("Usuario");
        jd_registrar.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));
        jd_registrar.getContentPane().add(pf_contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 150, 30));

        jb_crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sign-up.png"))); // NOI18N
        jb_crear.setText("Crear Solista");
        jb_crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearMouseClicked(evt);
            }
        });
        jd_registrar.getContentPane().add(jb_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 160, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logout.png"))); // NOI18N
        jButton2.setText("Regresar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jd_registrar.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 150, 40));

        jButton1.setText("Crear Bandas");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jd_registrar.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 110, 40));

        jButton3.setText("Crear Usuario");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jd_registrar.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 120, 40));

        pb_registro.setMaximum(5);
        jd_registrar.getContentPane().add(pb_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 320, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/papers.co-se68-blurry-background-sunrise-gradation-blur-40-wallpaper.jpg"))); // NOI18N
        jd_registrar.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 440));

        jd_admin.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setText("Ver Tabla");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jd_admin.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        elim.setText("Eliminar usuarios");
        elim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elimMouseClicked(evt);
            }
        });
        jd_admin.getContentPane().add(elim, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 130, -1));

        jButton5.setText("Eliminar Solista");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jd_admin.getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 130, -1));

        jButton6.setText("Eliminar Banda");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jd_admin.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 130, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/free-blurry-background-1636594.jpg"))); // NOI18N
        jd_admin.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 370));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Accion", "Tiempo", "Persona"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jd_tablaAdminLayout = new javax.swing.GroupLayout(jd_tablaAdmin.getContentPane());
        jd_tablaAdmin.getContentPane().setLayout(jd_tablaAdminLayout);
        jd_tablaAdminLayout.setHorizontalGroup(
            jd_tablaAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_tablaAdminLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jd_tablaAdminLayout.setVerticalGroup(
            jd_tablaAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_tablaAdminLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

        jButton8.setText("Eliminar");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        cb_artistas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_artistasItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jd_eliminarLayout = new javax.swing.GroupLayout(jd_eliminar.getContentPane());
        jd_eliminar.getContentPane().setLayout(jd_eliminarLayout);
        jd_eliminarLayout.setHorizontalGroup(
            jd_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_eliminarLayout.createSequentialGroup()
                .addGroup(jd_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_eliminarLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jButton8))
                    .addGroup(jd_eliminarLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(cb_artistas, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        jd_eliminarLayout.setVerticalGroup(
            jd_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_eliminarLayout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(cb_artistas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(jButton8)
                .addGap(95, 95, 95))
        );

        jButton9.setText("Eliminar");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        cb_sol.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_solItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jd_elimSolLayout = new javax.swing.GroupLayout(jd_elimSol.getContentPane());
        jd_elimSol.getContentPane().setLayout(jd_elimSolLayout);
        jd_elimSolLayout.setHorizontalGroup(
            jd_elimSolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_elimSolLayout.createSequentialGroup()
                .addGroup(jd_elimSolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_elimSolLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jButton9))
                    .addGroup(jd_elimSolLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(cb_sol, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jd_elimSolLayout.setVerticalGroup(
            jd_elimSolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_elimSolLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(cb_sol, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(jButton9)
                .addGap(95, 95, 95))
        );

        jButton10.setText("Eliminar");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        cb_ban.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_banItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jd_elimBanLayout = new javax.swing.GroupLayout(jd_elimBan.getContentPane());
        jd_elimBan.getContentPane().setLayout(jd_elimBanLayout);
        jd_elimBanLayout.setHorizontalGroup(
            jd_elimBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_elimBanLayout.createSequentialGroup()
                .addGroup(jd_elimBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_elimBanLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(cb_ban, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_elimBanLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jButton10)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jd_elimBanLayout.setVerticalGroup(
            jd_elimBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_elimBanLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(cb_ban, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jButton10)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jButton7.setText("Crear Cancion");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton11.setText("Crear Evento");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_artistaLayout = new javax.swing.GroupLayout(jd_artista.getContentPane());
        jd_artista.getContentPane().setLayout(jd_artistaLayout);
        jd_artistaLayout.setHorizontalGroup(
            jd_artistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_artistaLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jButton7)
                .addGap(81, 81, 81)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jd_artistaLayout.setVerticalGroup(
            jd_artistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_artistaLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(jd_artistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton11))
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jd_evento.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("Ciudad");
        jd_evento.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jLabel13.setText("Lugar");
        jd_evento.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        jLabel14.setText("Max. Personas");
        jd_evento.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        jLabel15.setText("Canciones");
        jd_evento.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jLabel16.setText("Fecha");
        jd_evento.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));
        jd_evento.getContentPane().add(tf_ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 110, 30));

        jp_personas.setModel(new javax.swing.SpinnerNumberModel(25, 1, null, 1));
        jd_evento.getContentPane().add(jp_personas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 80, 30));
        jd_evento.getContentPane().add(dc_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));
        jd_evento.getContentPane().add(tf_lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 110, 30));

        jButton13.setText("Añadir Canciones");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        jd_evento.getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 160, 30));

        jButton15.setText("Crear Evento");
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });
        jd_evento.getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        pb_evento.setMaximum(8);
        jd_evento.getContentPane().add(pb_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 320, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/free-blurry-background-1636594.jpg"))); // NOI18N
        jd_evento.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 369));

        jd_cancion.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Nombre");
        jd_cancion.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        jLabel8.setText("Segundos");
        jd_cancion.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));
        jd_cancion.getContentPane().add(tf_nomCan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 150, 30));

        jp_segundos.setModel(new javax.swing.SpinnerNumberModel(60, 45, null, 1));
        jd_cancion.getContentPane().add(jp_segundos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 80, 20));

        jButton12.setText("Crear");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        jd_cancion.getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 90, 30));

        jLabel10.setText("Crear Canciones");
        jd_cancion.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/papers.co-se68-blurry-background-sunrise-gradation-blur-40-wallpaper.jpg"))); // NOI18N
        jd_cancion.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 340));

        jd_agregarC.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cb_canciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jd_agregarC.getContentPane().add(cb_canciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 110, 40));

        jButton14.setText("Agregar");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });
        jd_agregarC.getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        pb_cancion.setMaximum(3);
        jd_agregarC.getContentPane().add(pb_cancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 320, 20));
        jd_agregarC.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 340));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("¿No tienes cuenta? Registrate");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));
        getContentPane().add(tf_userL, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 230, 30));
        getContentPane().add(pf_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 230, 20));

        jb_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tick.png"))); // NOI18N
        jb_login.setText("Log in");
        jb_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_loginMouseClicked(evt);
            }
        });
        getContentPane().add(jb_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 110, 30));

        jb_ingresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sign-up.png"))); // NOI18N
        jb_ingresar.setText("Registrate");
        jb_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ingresarMouseClicked(evt);
            }
        });
        getContentPane().add(jb_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 130, 40));

        lb_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/login.png"))); // NOI18N
        getContentPane().add(lb_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_loginMouseClicked
        // TODO add your handling code here:
        boolean flag = true;
        while (flag) {
            adminBanda ban = new adminBanda("./Banda.cbm");
            ban.cargarArchivo();
            ArrayList band = ban.getListaBandas();

            adminSolista sol = new adminSolista("./Solista.cbm");
            sol.cargarArchivo();
            ArrayList soli = sol.getListaSolista();

            adminUsuario us = new adminUsuario("./Usuario.cbm");
            us.cargarArchivo();
            ArrayList usu = us.getlistaUsuarios();

            for (int i = 0; i < band.size(); i++) {
                if (((Banda) band.get(i)).getUsuario().equals(tf_userL.getText()) && ((Banda) band.get(i)).getContrasena().equals(pf_contra.getText())) {

                    JOptionPane.showMessageDialog(null, "Se inició sesión con éxito");
                    quien = "banda";
                    pos = i;
                    jd_artista.pack();
                    jd_artista.setModal(true);
                    jd_artista.setLocationRelativeTo(this);
                    jd_artista.setVisible(true);
                    flag = false;
                    break;
                }
            }

            for (int i = 0; i < soli.size(); i++) {
                if (((Solista) soli.get(i)).getUsuario().equals(tf_userL.getText()) && ((Solista) soli.get(i)).getContrasena().equals(pf_contra.getText())) {

                    JOptionPane.showMessageDialog(null, "Se inició sesión con éxito");
                    quien = "solista";
                    pos = i;
                    jd_artista.pack();
                    jd_artista.setModal(true);
                    jd_artista.setLocationRelativeTo(this);
                    jd_artista.setVisible(true);
                    flag = false;
                    break;
                }
            }
            for (int i = 0; i < usu.size(); i++) {
                if (((Usuario) usu.get(i)).getUsuario().equals(tf_userL.getText()) && ((Usuario) usu.get(i)).getContrasena().equals(pf_contra.getText())) {

                    JOptionPane.showMessageDialog(null, "Se inició sesión con éxito");

//                jd_chat.pack();
//                jd_chat.setModal(true);
//                jd_chat.setLocationRelativeTo(this);
//                jd_chat.setVisible(true);
                    flag = false;
                    break;
                }
            }

            if (admin.equals(tf_userL.getText()) && admincon.equals(pf_contra.getText())) {
                jd_admin.pack();
                jd_admin.setModal(true);
                jd_admin.setLocationRelativeTo(this);
                jd_admin.setVisible(true);
                break;
            }

        }

        tf_userL.setText("");
        pf_contra.setText("");
    }//GEN-LAST:event_jb_loginMouseClicked

    private void jb_ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ingresarMouseClicked
        // TODO add your handling code here:

        jd_registrar.pack();
        jd_registrar.setModal(true);
        jd_registrar.setLocationRelativeTo(this);
        jd_registrar.setVisible(true);

    }//GEN-LAST:event_jb_ingresarMouseClicked

    private void jb_crearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearMouseClicked
        String ed = JOptionPane.showInputDialog("Ingrese la edad");
        edad = Integer.parseInt(ed);
        genero = JOptionPane.showInputDialog("Ingrese el genero musical");

        adminSolista l = new adminSolista("./Solista.cbm");

        Solista solista = new Solista(genero, edad, tf_display.getText(), pf_contrasena.getText(), tf_username.getText());

        l.cargarArchivo();
        l.setSolista(solista);
        l.escribirArchivo();

        DefaultComboBoxModel modelo = new DefaultComboBoxModel(l.getListaSolista().toArray());
        cb_sol.setModel(modelo);

        h = new Hilo(pb_registro);

        h.setTiempo(5);
        h.start();

        JOptionPane.showMessageDialog(null, "Solista creado con exito");

        tf_username.setText("");
        pf_contrasena.setText("");
        tf_display.setText("");


    }//GEN-LAST:event_jb_crearMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        jd_registrar.pack();
        jd_registrar.setModal(false);
        jd_registrar.setLocationRelativeTo(this);
        jd_registrar.setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String inte = JOptionPane.showInputDialog("Ingrese el numero de integrantes");
        integrantes = Integer.parseInt(inte);
        genero = JOptionPane.showInputDialog("Ingrese el genero musical");

        adminBanda l = new adminBanda("./Banda.cbm");

        Banda banda = new Banda(genero, integrantes, tf_display.getText(), pf_contrasena.getText(), tf_username.getText());

        l.cargarArchivo();
        l.setBanda(banda);
        l.escribirArchivo();

        DefaultComboBoxModel modelo = new DefaultComboBoxModel(l.getListaBandas().toArray());
        cb_sol.setModel(modelo);

        h = new Hilo(pb_registro);

        h.setTiempo(5);
        h.start();

        JOptionPane.showMessageDialog(null, "Banda creado con exito");

        tf_username.setText("");
        pf_contrasena.setText("");
        tf_display.setText("");
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        String ed = JOptionPane.showInputDialog("Ingrese la edad");
        edad = Integer.parseInt(ed);

        adminUsuario l = new adminUsuario("./Usuario.cbm");

        Usuario usuario = new Usuario(edad, tf_display.getText(), pf_contrasena.getText(), tf_username.getText());

        l.cargarArchivo();
        l.setUsuario(usuario);
        l.escribirArchivo();

        DefaultComboBoxModel modelo = new DefaultComboBoxModel(l.getlistaUsuarios().toArray());
        cb_artistas.setModel(modelo);

        h = new Hilo(pb_registro);

        h.setTiempo(5);
        h.start();

        JOptionPane.showMessageDialog(null, "Usuario creado con exito");

        tf_username.setText("");
        pf_contrasena.setText("");
        tf_display.setText("");
    }//GEN-LAST:event_jButton3MouseClicked

    private void elimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elimMouseClicked
        // TODO add your handling code here:
        jd_eliminar.pack();
        jd_eliminar.setModal(true);
        jd_eliminar.setLocationRelativeTo(this);
        jd_eliminar.setVisible(true);
    }//GEN-LAST:event_elimMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        jd_tablaAdmin.pack();
        jd_tablaAdmin.setModal(true);
        jd_tablaAdmin.setLocationRelativeTo(this);
        jd_tablaAdmin.setVisible(true);


    }//GEN-LAST:event_jButton4MouseClicked

    private void cb_artistasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_artistasItemStateChanged
        // TODO add your handling code here:

        adminUsuario l = new adminUsuario("./Usuario.cbm");
        l.cargarArchivo();
        DefaultComboBoxModel modelo = new DefaultComboBoxModel(l.getlistaUsuarios().toArray());
        cb_artistas.setModel(modelo);


    }//GEN-LAST:event_cb_artistasItemStateChanged

    private void cb_solItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_solItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_solItemStateChanged

    private void cb_banItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_banItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_banItemStateChanged

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        adminUsuario ap = new adminUsuario("./Usuario.cbm");
        ap.cargarArchivo();
        ap.getlistaUsuarios().remove(cb_artistas.getSelectedIndex());
        ap.escribirArchivo();

        DefaultComboBoxModel modelo = new DefaultComboBoxModel(ap.getlistaUsuarios().toArray());
        cb_artistas.setModel(modelo);
        JOptionPane.showMessageDialog(null, "Usuario eliminado exitosamente");
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        jd_elimSol.pack();
        jd_elimSol.setModal(true);
        jd_elimSol.setLocationRelativeTo(this);
        jd_elimSol.setVisible(true);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        jd_elimBan.pack();
        jd_elimBan.setModal(true);
        jd_elimBan.setLocationRelativeTo(this);
        jd_elimBan.setVisible(true);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        adminSolista ap = new adminSolista("./Solista.cbm");

        ap.cargarArchivo();
        ap.getListaSolista().remove(cb_sol.getSelectedIndex());
        ap.escribirArchivo();

        DefaultComboBoxModel modelo = new DefaultComboBoxModel(ap.getListaSolista().toArray());
        cb_sol.setModel(modelo);
        JOptionPane.showMessageDialog(null, "Solista eliminado exitosamente");
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:
        adminBanda ap = new adminBanda("./Banda.cbm");

        ap.cargarArchivo();
        ap.getListaBandas().remove(cb_ban.getSelectedIndex());
        ap.escribirArchivo();

        DefaultComboBoxModel modelo = new DefaultComboBoxModel(ap.getListaBandas().toArray());
        cb_ban.setModel(modelo);
        JOptionPane.showMessageDialog(null, "Solista eliminado exitosamente");
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        // TODO add your handling code here:
        if (quien.equals("banda")) {

            adminBanda ban = new adminBanda("./Banda.cbm");
            ban.cargarArchivo();
            String dura = jp_segundos.getValue().toString();
            int duracion = Integer.parseInt(dura);
            ban.getListaBandas().get(pos).getListaCanciones().add(new Cancion(tf_nomCan.getText(), duracion));
            ban.escribirArchivo();
            JOptionPane.showMessageDialog(null, "Se creo con exito");
        } else if (quien.equals("solista")) {
            adminSolista sol = new adminSolista("./Solista.cbm");
            sol.cargarArchivo();
            String dura = jp_segundos.getValue().toString();
            int duracion = Integer.parseInt(dura);
            sol.getListaSolista().get(pos).getListaCanciones().add(new Cancion(tf_nomCan.getText(), duracion));
            sol.escribirArchivo();
            JOptionPane.showMessageDialog(null, "Se creo con exito");
        }
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        jd_cancion.pack();
        jd_cancion.setModal(true);
        jd_cancion.setLocationRelativeTo(this);
        jd_cancion.setVisible(true);
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:
        canciones = new ArrayList();
        jd_evento.pack();
        jd_evento.setModal(true);
        jd_evento.setLocationRelativeTo(this);
        jd_evento.setVisible(true);
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        // TODO add your handling code here:

        canciones.add(((Cancion) cb_canciones.getSelectedItem()));
        h = new Hilo(pb_cancion);

        h.setTiempo(3);
        h.start();
    }//GEN-LAST:event_jButton14MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        // TODO add your handling code here:
        if (quien.equals("banda")) {

            adminBanda ban = new adminBanda("./Banda.cbm");
            ban.cargarArchivo();

            DefaultComboBoxModel modelo = new DefaultComboBoxModel(ban.getListaBandas().get(pos).getListaCanciones().toArray());
            cb_canciones.setModel(modelo);

        } else if (quien.equals("solista")) {
            adminSolista sol = new adminSolista("./Solista.cbm");
            sol.cargarArchivo();

            DefaultComboBoxModel modelo = new DefaultComboBoxModel(sol.getListaSolista().get(pos).getListaCanciones().toArray());
            cb_canciones.setModel(modelo);

        }

        jd_agregarC.pack();
        jd_agregarC.setModal(true);
        jd_agregarC.setLocationRelativeTo(this);
        jd_agregarC.setVisible(true);
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
        // TODO add your handling code here:
        Date fe = dc_fecha.getDate();
        String ciudad = tf_ciudad.getText();
        String lugar = tf_lugar.getText();
        String perso = jp_personas.getValue().toString();
        int personas = Integer.parseInt(perso);

        eventos.add(new Evento(fe, ciudad, lugar, personas));

        int numEvento = eventos.size() - 1;
        eventos.get(numEvento).setListaCancion(canciones);
                h = new Hilo(pb_evento);

        h.setTiempo(8);
        h.start();
        JOptionPane.showMessageDialog(null, "Se creo con exito");

        

    }//GEN-LAST:event_jButton15MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_artistas;
    private javax.swing.JComboBox<String> cb_ban;
    private javax.swing.JComboBox<String> cb_canciones;
    private javax.swing.JComboBox<String> cb_sol;
    private com.toedter.calendar.JDateChooser dc_fecha;
    private javax.swing.JButton elim;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jb_crear;
    private javax.swing.JButton jb_ingresar;
    private javax.swing.JButton jb_login;
    private javax.swing.JDialog jd_admin;
    private javax.swing.JDialog jd_agregarC;
    private javax.swing.JDialog jd_artista;
    private javax.swing.JDialog jd_cancion;
    private javax.swing.JDialog jd_elimBan;
    private javax.swing.JDialog jd_elimSol;
    private javax.swing.JDialog jd_eliminar;
    private javax.swing.JDialog jd_evento;
    private javax.swing.JDialog jd_registrar;
    private javax.swing.JDialog jd_tablaAdmin;
    private javax.swing.JSpinner jp_personas;
    private javax.swing.JSpinner jp_segundos;
    private javax.swing.JLabel lb_foto;
    private javax.swing.JProgressBar pb_cancion;
    private javax.swing.JProgressBar pb_evento;
    private javax.swing.JProgressBar pb_registro;
    private javax.swing.JPasswordField pf_contra;
    private javax.swing.JPasswordField pf_contrasena;
    private javax.swing.JTextField tf_ciudad;
    private javax.swing.JTextField tf_display;
    private javax.swing.JTextField tf_lugar;
    private javax.swing.JTextField tf_nomCan;
    private javax.swing.JTextField tf_userL;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
    Hilo h;
    ArrayList<Evento> eventos = new ArrayList();
    ArrayList<Cancion> canciones;
    String quien;
    int pos;
    String genero;
    int edad;
    int integrantes;
    String admin = "leobanegas";
    String admincon = "99";
}
