/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7_paulinaeuceda;

/**
 *
 * @author euced
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        tf_userL = new javax.swing.JTextField();
        pf_contra = new javax.swing.JPasswordField();
        jb_login = new javax.swing.JButton();
        jb_ingresar = new javax.swing.JButton();
        lb_foto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("¿No tienes cuenta? Registrate");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));
        getContentPane().add(tf_userL, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 230, 30));
        getContentPane().add(pf_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 230, 20));

        jb_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tick.png"))); // NOI18N
        jb_login.setText("Log in");
        jb_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_loginMouseClicked(evt);
            }
        });
        getContentPane().add(jb_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 110, 30));

        jb_ingresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sign-up.png"))); // NOI18N
        jb_ingresar.setText("Registrate");
        jb_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ingresarMouseClicked(evt);
            }
        });
        getContentPane().add(jb_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 130, 40));

        lb_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/login.png"))); // NOI18N
        getContentPane().add(lb_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_loginMouseClicked
        // TODO add your handling code here:

        administrarContactos ap = new administrarContactos("./Users.txt");
        ap.cargarArchivo();

        ArrayList o = ap.getListaContactos();

        DefaultListModel modelo = new DefaultListModel();

        System.out.println(o);

        for (int i = 0; i < o.size(); i++) {
            modelo.addElement(o.get(i));
        }

        jl_contactos.setModel(modelo);

        for (int i = 0; i < o.size(); i++) {
            if (((Contactos) o.get(i)).getDisplay().equals(tf_userL.getText()) && ((Contactos) o.get(i)).getContrasena().equals(pf_contra.getText())) {
                JOptionPane.showMessageDialog(null, "Se inició sesión con éxito");
                nombre = tf_userL.getText();
                ta_maquina.setText(nombre + ": ");
                jd_chat.pack();
                jd_chat.setModal(true);
                jd_chat.setLocationRelativeTo(this);
                jd_chat.setVisible(true);

                break;
            }
        }
        tf_userL.setText("");
        pf_contra.setText("");
    }//GEN-LAST:event_jb_loginMouseClicked

    private void jb_ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ingresarMouseClicked
        // TODO add your handling code here:

        jd_registrar.pack();
        jd_registrar.setModal(true);
        jd_registrar.setLocationRelativeTo(this);
        jd_registrar.setVisible(true);

    }//GEN-LAST:event_jb_ingresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jb_ingresar;
    private javax.swing.JButton jb_login;
    private javax.swing.JLabel lb_foto;
    private javax.swing.JPasswordField pf_contra;
    private javax.swing.JTextField tf_userL;
    // End of variables declaration//GEN-END:variables
}
